# docker-compose.yml
version: '3.7'

services: 
  flask:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    working_dir: /app
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      - FLASK_ENV="production"

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    # directorios para el archivo de configuracion y archivos del static
    volumes:
    - ./conf:/etc/nginx/conf.d
    - ./app/static:/var/www/static
    depends_on:
    - flask
